// <auto-generated />
using EMSAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMSAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609041014_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMSAPI.Models.Movement", b =>
                {
                    b.Property<int>("MoveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoveID"));

                    b.Property<int>("ButtonSignal")
                        .HasColumnType("int");

                    b.Property<string>("DataFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SensorSignal")
                        .HasColumnType("int");

                    b.HasKey("MoveID");

                    b.ToTable("Movements");

                    b.HasData(
                        new
                        {
                            MoveID = 1,
                            ButtonSignal = 1,
                            DataFrom = "Frontend",
                            Message = "You Got Mail!",
                            SensorSignal = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
